insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Pulp Fiction', 2015, 4.2, 3, 'crime');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Matrix', 2015, 5, 1, 'drama');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Shawshank Redemption', 2018, 4.5, 2, 'family');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Inception', 2013, 3.2, 2, 'musical');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Matrix', 2007, 2.7, 3, 'sci-fi');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Godfather', 1998, 4.2, 4, 'comedy');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Godfather', 1998, 4.5, 1, 'romance');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Dark Knight', 2015, 4.2, 2, 'musical');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Pulp Fiction', 2005, 4.5, 4, 'western');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Inception', 1992, 3.2, 2, 'sports');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Inception', 2015, 4.2, 3, 'horror');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Matrix', 2005, 3.2, 2, 'horror');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Pulp Fiction', 2018, 2.9, 2, 'thriller');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Inception', 1998, 4.8, 1, 'western');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Schindler''s List', 2005, 4.6, 2, 'fantasy');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Lord of the Rings: The Fellowship of the Ring', 2021, 4.2, 1, 'family');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Goodfellas', 1992, 2.9, 4, 'musical');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Schindler''s List', 2015, 3.2, 2, 'historical');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Fight Club', 2015, 3.9, 1, 'sports');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Dark Knight', 1992, 3.2, 2, 'action');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Fight Club', 2013, 5, 2, 'romance');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Schindler''s List', 2013, 4.2, 3, 'drama');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Pulp Fiction', 1998, 4.8, 3, 'war');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Schindler''s List', 1998, 2.9, 1, 'adventure');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('Inception', 1992, 2.7, 2, 'musical');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Shawshank Redemption', 2018, 5, 2, 'horror');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Dark Knight', 1998, 3.5, 3, 'animation');
insert into tblfilms (title, yearReleased, rating, duration, genre) values ('The Matrix', 2013, 4.6, 4, 'drama');