-- SQLite
insert into songs (Title, Artist, Genre) values ('Imagine', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Sophia Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Thriller', 'Sophia Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Michael Davis', 'horror');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Daniel Martinez', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Emma Taylor', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'John Smith', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Olivia Anderson', 'horror');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('Like a Rolling Stone', 'David Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Sophia Thompson', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Ava Hernandez', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Like a Rolling Stone', 'John Smith', 'horror');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Matthew Garcia', 'drama');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Ava Hernandez', 'romance');
insert into songs (Title, Artist, Genre) values ('Thriller', 'Daniel Martinez', 'horror');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Ava Hernandez', 'thriller');
insert into songs (Title, Artist, Genre) values ('Thriller', 'David Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Emma Taylor', 'horror');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Daniel Martinez', 'drama');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Emily Johnson', 'horror');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Emma Taylor', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Daniel Martinez', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Like a Rolling Stone', 'Sophia Thompson', 'romance');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'John Smith', 'thriller');
insert into songs (Title, Artist, Genre) values ('Thriller', 'Emily Johnson', 'action');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Matthew Garcia', 'mystery');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Ava Hernandez', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'David Wilson', 'action');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Michael Davis', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Olivia Anderson', 'horror');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Michael Davis', 'drama');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Matthew Garcia', 'romance');
insert into songs (Title, Artist, Genre) values ('Thriller', 'Ava Hernandez', 'thriller');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'David Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Ava Hernandez', 'comedy');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Ava Hernandez', 'action');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Olivia Anderson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Ava Hernandez', 'horror');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'David Wilson', 'adventure');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Emma Taylor', 'horror');
insert into songs (Title, Artist, Genre) values ('Thriller', 'David Wilson', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Matthew Garcia', 'adventure');
insert into songs (Title, Artist, Genre) values ('Like a Rolling Stone', 'Olivia Anderson', 'drama');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Ava Hernandez', 'adventure');
insert into songs (Title, Artist, Genre) values ('Thriller', 'Daniel Martinez', 'drama');
insert into songs (Title, Artist, Genre) values ('Like a Rolling Stone', 'Sophia Thompson', 'drama');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'John Smith', 'comedy');
insert into songs (Title, Artist, Genre) values ('Like a Rolling Stone', 'Emma Taylor', 'thriller');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Ava Hernandez', 'thriller');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Emma Taylor', 'adventure');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Thriller', 'Sophia Thompson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('Thriller', 'Matthew Garcia', 'adventure');
insert into songs (Title, Artist, Genre) values ('Like a Rolling Stone', 'David Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('Thriller', 'Michael Davis', 'romance');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'David Wilson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'David Wilson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Like a Rolling Stone', 'Olivia Anderson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Michael Davis', 'comedy');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Matthew Garcia', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Imagine', 'David Wilson', 'horror');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'John Smith', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Sophia Thompson', 'horror');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Daniel Martinez', 'fantasy');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Daniel Martinez', 'adventure');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Emily Johnson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'David Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Matthew Garcia', 'drama');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Emily Johnson', 'drama');
insert into songs (Title, Artist, Genre) values ('Imagine', 'David Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'John Smith', 'mystery');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Emily Johnson', 'romance');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Michael Davis', 'adventure');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Olivia Anderson', 'thriller');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Michael Davis', 'mystery');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Matthew Garcia', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Sophia Thompson', 'comedy');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Daniel Martinez', 'romance');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Matthew Garcia', 'sci-fi');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Sophia Thompson', 'mystery');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Olivia Anderson', 'drama');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'David Wilson', 'romance');
insert into songs (Title, Artist, Genre) values ('Like a Rolling Stone', 'Daniel Martinez', 'horror');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'David Wilson', 'drama');
